REGION_MAPPING = {
    "United States": "North America",
    "Canada": "North America",
    "Brazil": "Other",
    "Germany": "Europe",
    "United Kingdom": "Europe",
    "France": "Europe",
    "Netherlands": "Europe",
    "Belgium": "Europe",
    "Spain": "Europe",
    "Italy": "Europe",
    "India": "Asia-Pacific",
    "Taiwan": "Asia-Pacific",
    "Japan": "Asia-Pacific",
    "South Korea": "Asia-Pacific",
    "Indonesia": "Asia-Pacific",
    "Hong Kong": "Asia-Pacific",
    "Australia": "Asia-Pacific",
}

ANATOMICAL_MAPPING = {
    "oral cavity, oropharynx, larynx": "oral cavity, oropharynx, larynx",
    "buccal mucosa": "oral cavity",
    "external auditory canal": "external auditory canal",
    "floor of mouth": "oral cavity",
    "glotti": "larynx",
    "head and neck": "head and neck",
    "hypopharyn": "hypopharynx",
    "laryn": "larynx",
    "major salivary": "salivary gland",
    "nasopharyn": "nasopharynx",
    "oral": "oral cavity",
    "oropharyn": "oropharynx",
    "parotid": "salivary gland",
    "salivary gland": "salivary gland",
    "scalp": "scalp",
    "sinonasal": "sinonasal",
    "tonsil": "oropharynx",
}

# in decreasing order of specificity considering the broad scope of some histologies
HISTO_MAPPING = {
    "sarcomatoid variant": "sarcoma",
    "squamous cell carcinoma": "squamous cell carcinoma",
    "cutaneous angiosarcoma": "sarcoma",
    "soft tissue sarcoma": "sarcoma",
    "angiosarcoma": "sarcoma",
    "carcinosarcoma": "sarcoma",
    "adenoid cystic carcinoma": "non-squamous carcinoma",
    "clear cell carcinoma": "non-squamous carcinoma",
    "small cell cancer": "non-squamous carcinoma",
    "cutaneous melanoma": "melanoma",
    "mucosal melanoma": "melanoma",
    "carcinoma": "carcinoma",
}

STAGE_MAPPING = {
    "3, 4a, 4b": "locally advanced",
    "ct1n0": "early",
    "ct1n0m0": "early",
    "i-ivb": "non metastatic",
    "ii-iii": "non metastatic",
    "ii-ivb": "non metastatic",
    "iii-iv": "non metastatic",
    "iii-ivb": "locally advanced",
    "iii-ivc": "advanced",
    "iv": "advanced",
    "ivc": "metastatic",
    "m1": "metastatic",
    "pt1-2n1m0": "early",
    "pt3-4n0-3m0, pt1-4n0-3m0": "non metastatic",
    "t1, t2": "early",
    "t1-2n0m0": "early",
    "t1-2n1": "early",
    "t1/2n0m0": "early",
    "t1a, t1b, t2": "early",
    "t2n0m0": "early",
    "t3/4, n0–3, m0": "locally advanced",
    "t3–4n2, t1–4n3, nonmetastatic": "locally advanced",
    "t4": "locally advanced",
    "t4a": "locally advanced",
    "t4b": "locally advanced",
    "tisn0m0, t1n0m0, t1an0m0, t1bn0m0, t2n0m0": "early",
}

ENDPOINT_MAPPING = {
    "Dysphagia Outcome and Severity Scale (DOSS) score": "toxicities and functional outcomes",
    "EORTC QLQ-C30 global health status and functional scale scores": "quality of life and patient reported outcomes",
    "EORTC QLQ-H&N35 multi-item scales and single items": "quality of life and patient reported outcomes",
    "EQ-5D-3L utility": "quality of life and patient reported outcomes",
    "SCCHN related emergency department visits": "healthcare utilisation",
    "SCCHN related hospitalisations": "healthcare utilisation",
    "SCCHN related office visits/consults": "healthcare utilisation",
    "SCCHN related outpatient palliative care visits": "healthcare utilisation",
    "SCCHN related outpatient visits in hospital clinics": "healthcare utilisation",
    "acute and late treatment toxicities": "toxicities and functional outcomes",
    "adherence to adjuvant therapy": "treatment tolerance and adherence",
    "all cause mortality": "survival outcomes",
    "all cause survival": "survival outcomes",
    "cancer-specific survival": "survival outcomes",
    "cancer specific mortality": "survival outcomes",
    "cancer specific survival": "survival outcomes",
    "cause specific survival": "survival outcomes",
    "complete response in definitive radiotherapy": "treatment response",
    "compliance": "treatment tolerance and adherence",
    "cumulative incidence of cancer specific death": "survival outcomes",
    "cumulative survival percentage": "survival outcomes",
    "delivery of boost dose radiotherapy": "treatment delivery",
    "disease-free survival": "recurrence outcomes",
    "disease free survival": "recurrence outcomes",
    "disease specific survival": "survival outcomes",
    "distant control": "recurrence outcomes",
    "distant failure-free survival": "recurrence outcomes",
    "distant metastases free survival": "recurrence outcomes",
    "distant recurrence rate": "recurrence outcomes",
    "extracapsular spread": None,
    "first primary treatment": "treatment delivery",
    "frequency of healthcare resource utilization": "healthcare utilisation",
    "gastrostomy rate at last contact": "toxicities and functional outcomes",
    "intent of treatment received": None,
    "local control": "recurrence outcomes",
    "local regional control rate": "recurrence outcomes",
    "locoregional control": "recurrence outcomes",
    "locoregional failure-free survival": "recurrence outcomes",
    "locoregional progression free survival": "recurrence outcomes",
    "locoregional recurrence rate": "recurrence outcomes",
    "observed survival": "survival outcomes",
    "other cause survival": "survival outcomes",
    "overall survival": "survival outcomes",
    "overall treatment regimen": "treatment delivery",
    "patient care monitor": "quality of life and patient reported outcomes",
    "post-salvage PEG-tubes use": "toxicities and functional outcomes",
    "post-salvage tracheostomies use": "toxicities and functional outcomes",
    "primary treatment": "treatment delivery",
    "progression free survival": "progression outcomes",
    "radiation related late toxicities": "toxicities and functional outcomes",
    "rate of healthcare resource utilization": "healthcare utilisation",
    "receipt of adjuvant chemoradiotherapy": "treatment delivery",
    "receipt of chemoradiotherapy": "treatment delivery",
    "receipt of surgery as primary treatment": "treatment delivery",
    "receiving induction chemotherapy": "treatment delivery",
    "recurrence": "recurrence outcomes",
    "recurrence free survival": "recurrence outcomes",
    "recurrence free survival rate": "recurrence outcomes",
    "regional control": "recurrence outcomes",
    "relative survival": "survival outcomes",
    "response to treatment": "treatment response",
    "stage at presentation": None,
    "surgical margins": "treatment delivery",
    "time to progression": "progression outcomes",
    "time to treatment initiation": "treatment delivery",
    "treatment duration": "treatment delivery",
    "treatment tolerance": "treatment tolerance and adherence",
    "treatment with adjuvant chemoradiotherapy": "treatment delivery",
    "tumor response": "treatment response",
    "ultimate local control": "recurrence outcomes",
    "ultimate nodal control": "recurrence outcomes",
    "use of any chemotherapy": "treatment delivery",
    "visual analog scale scores": "quality of life and patient reported outcomes",
}

SOURCE_MAPPING = {
    "Adelphi Real World SCCHN Disease Specific Program retrospective chart analysis, cross-sectional patient-reported outcome data capture": [
        "collaborative chart review",
        "patient reported outcomes",
    ],
    "Eviti Connect decision support platform": ["healthcare systems or platforms"],
    "Head and Neck Anthology system": ["healthcare systems or platforms"],
    "Head and Neck Anthology system and the RT records": [
        "healthcare systems or platforms"
    ],
    "Kaiser Permanente Northern California integrated health care system": [
        "healthcare systems or platforms"
    ],
    "Longitudinal Oncology Registry of Head and Neck Carcinoma national registry": [
        "cancer registry"
    ],
    "National Centre for Disease Informatics and Research repository from standardised patient information form": [
        "national database"
    ],
    "Prince of Wales Hospital Cancer Centre Oral Cavity Database": [
        "single center database"
    ],
    "Thuringian cancer registry": ["cancer registry"],
    "administrative claims data fromThomson Reuters MarketScan Databases": [
        "administrative and claims database"
    ],
    "automated head and neck surgery division new referrals report, weekly multidisciplinary tumor board reports, cancer registry": [
        "medical record",
        "cancer registry",
    ],
    "cancer registry linked with hospital discharge, death registry, census, patient information system, and treatment center database": [
        "cancer registry",
        "administrative and claims database",
        "death registry",
        "census",
        "healthcare systems or platforms",
        "multiple centers database",
    ],
    "chart review and cancer registry": ["medical record", "cancer registry"],
    "chart review of Japan Clinical Oncology Group Head and Neck Cancer Study Group": [
        "collaborative chart review"
    ],
    "electronic medical records, patient-reported outcomes data from patient care monitors, and notes from health care providers": [
        "medical record",
        "patient reported outcomes",
    ],
    "electronic patient record system of hong kong hospital authority sampling from hong kong cancer registry": [
        "cancer registry",
        "medical record",
    ],
    "glance multinational retrospective manual chart review into an electronic case report form": [
        "collaborative chart review"
    ],
    "iKnowMed database oncology specific ehr, medical chart abstraction, vital status from social security death index": [
        "healthcare systems or platforms",
        "medical record",
        "death registry",
    ],
    "linkage of Belgian Cancer Registry database, database of the Intermutualistic Agency, hospital discharge database": [
        "cancer registry",
        "national database",
        "administrative and claims database",
    ],
    "lorhan registry database": ["cancer registry"],
    "medical record": ["medical record"],
    "medical record from cancer registry sampling frame": [
        "medical record",
        "cancer registry",
    ],
    "medical records and cancer registry": ["medical record", "cancer registry"],
    "multi-institutional retrospective\nstudy (Korean Radiation Oncology Group) medical records": [
        "collaborative chart review"
    ],
    "multiple centers database": ["multiple centers database"],
    "ncdb": ["national database"],
    "netherlands cancer registry (cases identified from pathology records from pathology network and hospital discharge registry)": [
        "cancer registry",
        "national database",
        "administrative and claims database",
    ],
    "patient record form": ["case report form"],
    "questionnaire survey": ["case report form"],
    "seer": ["national database"],
    "seer poc": ["national database"],
    "single center database": ["single center database"],
}

INCLUSION_MAPPING = {
    "cancer_site": "anatomical site",
    "cancer_type": "histology",
    "clinical_trial_participation": "clinical trial participation",
    "diagnosis_confirmation": "diagnosis confirmation",
    "disease_stage": "stage",
    "eligibility_for_intervention": "eligibility for intervention",
    "follow_up_status": "follow up status",
    "institution": "treatment location",
    "metastatic_status": "stage",
    "performance_status": "performance status",
    "treatment_intent": "treatment intent",
    "treatment_timing": "treatment timing",
    "treatment_type": "treatment type",
}

EXCLUSION_MAPPING = {
    "cancer_site": "anatomical site",
    "clinical_trial_participation": "clinical trial participation",
    "data_availability": "data availability",
    "disease_stage": "stage",
    "follow_up_duration": "follow up duration",
    "insurance_type": "insurance type",
    "metastatic_status": "metastatic status",
    "pathologic_staging": "pathologic staging",
    "previous_malignancy": "previous malignancy",
    "prior_treatment": "prior treatment",
    "survival_outcome": "follow up duration",
    "treatment_dose": "treatment dose",
    "treatment_location": "treatment location",
    "treatment_status": "treatment status",
    "treatment_timing": "treatment timing",
    "treatment_type": "treatment type",
}

DOI_SPECIFIC_MAPPING = [
    {
        "doi": [
            "https://doi.org/10.1016/j.ijrobp.2017.03.019",
        ],
        "mapping": {"income quartile": "median income of patient's zip code"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.ijrobp.2011.11.067"],
        "mapping": {"income quartile": "median income of patient's census tract"},
    },
    {
        "doi": [
            "https://doi.org/10.1002/hed.25808",
            "https://doi.org/10.1002/cncr.28870",
            "https://doi.org/10.1016/j.ijrobp.2017.01.224",
            "https://doi.org/10.1016/j.oraloncology.2017.06.013",
        ],
        "mapping": {"income": "median income of patient's zip code"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.28083"],
        "mapping": {"income": "median income"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.25430"],
        "mapping": {"median income": "median income of patient's zip code"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.28870"],
        "mapping": {
            "distance": "distance from the patient’s zip code to treatment facility"
        },
    },
    {
        "doi": [
            "https://doi.org/10.1016/j.ijrobp.2017.03.050",
            "https://doi.org/10.1016/j.oraloncology.2017.07.013",
        ],
        "mapping": {"comorbidity": "charlson-deyo comorbidity score"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.radonc.2017.03.019"],
        "mapping": {"comorbidities": "charlson-deyo comorbidity score"},
    },
    {
        "doi": ["https://doi.org/10.1002/cam4.4204"],
        "mapping": {"histology": "who histology"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.28936"],
        "mapping": {"recurrence": "recurrence site"},
    },
    {
        "doi": ["https://doi.org/10.7314/APJCP.2016.17.4.1745"],
        "mapping": {"recurrence": "recurrence status"},
    },
    {
        "doi": [
            "https://doi.org/10.4143/crt.2015.265",
            "https://doi.org/10.1016/j.oooo.2020.01.006",
            "https://doi.org/10.1002/lary.24296",
        ],
        "mapping": {"ajcc stage": "ajcc 6th edition stage"},
    },
    {
        "doi": [
            "https://doi.org/10.1002/lary.24296",
            "https://doi.org/10.4143/crt.2015.265",
            "https://doi.org/10.1186/1916-0216-43-19",
        ],
        "mapping": {"n stage": "ajcc 6th edition n category"},
    },
    {
        "doi": [
            "https://doi.org/10.1002/lary.24296",
            "https://doi.org/10.4143/crt.2015.265",
            "https://doi.org/10.1186/1916-0216-43-19",
            "https://doi.org/10.1016/j.ijrobp.2017.01.209",
        ],
        "mapping": {"t stage": "ajcc 6th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1097/MD.0000000000029285"],
        "mapping": {"clinical n stage": "ajcc 7th 8th edition clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.oraloncology.2017.08.002"],
        "mapping": {"clinical n stage": "ajcc 7th edition clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.26903"],
        "mapping": {"clinical n stage": "ajcc clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.26903"],
        "mapping": {"clinical t stage": "ajcc clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.oraloncology.2017.08.002"],
        "mapping": {"clinical t stage": "ajcc 7th edition clinical t category"},
    },
    {
        "doi": [
            "https://doi.org/10.1007/s00405-019-05282-2",
            "https://doi.org/10.1001/jamaoto.2016.1162",
            "https://doi.org/10.1016/j.ijrobp.2017.03.019",
        ],
        "mapping": {"pathologic n stage": "ajcc pathological n category"},
    },
    {
        "doi": [
            "https://doi.org/10.1007/s00405-019-05282-2",
            "https://doi.org/10.1001/jamaoto.2016.1162",
            "https://doi.org/10.1016/j.ijrobp.2017.03.019",
        ],
        "mapping": {"pathologic t stage": "ajcc pathological t category"},
    },
    {
        "doi": [
            "https://doi.org/10.1016/j.ijrobp.2017.03.019",
        ],
        "mapping": {"t stage": "ajcc clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.30255"],
        "mapping": {"clinical n classification": "ajcc clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.4103/crst.crst_148_21"],
        "mapping": {"clinical stage": "ajcc 8th edition clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.30255"],
        "mapping": {"clinical t classification": "ajcc clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.25808"],
        "mapping": {"hpv status": "high risk hpv status"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.30255"],
        "mapping": {"hpv status": "hpv status type 16 18"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.28083"],
        "mapping": {"hpv status": "hpv status type 16 and or 18 ish and or ihc p16"},
    },
    {
        "doi": ["https://doi.org/10.1001/jamaoto.2016.1162"],
        "mapping": {
            "human papillomavirus status": "hpv status type 16 18 no specified method without p16"
        },
    },
    {
        "doi": ["https://doi.org/10.1002/hed.23777"],
        "mapping": {"m classification": "tnm 6th edition clinical m category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.23777"],
        "mapping": {"n classification": "tnm 6th edition clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.23777"],
        "mapping": {"t classification": "tnm 6th edition clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.23777"],
        "mapping": {"tnm classification": "tnm 6th edition stage"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.25430"],
        "mapping": {"m classification": "ajcc 6th 7th edition m category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.25430"],
        "mapping": {"n classification": "ajcc 6th 7th edition n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.25430"],
        "mapping": {"t classification": "ajcc 6th 7th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1007/s00432-015-1961-y"],
        "mapping": {"m classification": "ajcc 7th edition m category"},
    },
    {
        "doi": ["https://doi.org/10.1007/s00432-015-1961-y"],
        "mapping": {"n classification": "ajcc 7th edition n category"},
    },
    {
        "doi": ["https://doi.org/10.1007/s00432-015-1961-y"],
        "mapping": {"t classification": "ajcc 7th edition t category"},
    },
    {
        "doi": [
            "https://doi.org/10.31557/APJCP.2020.21.5.1481",
            "https://doi.org/10.1186/s13014-020-1481-z",
        ],
        "mapping": {"m stage": "uicc 7th edition m category"},
    },
    {
        "doi": [
            "https://doi.org/10.31557/APJCP.2020.21.5.1481",
            "https://doi.org/10.1186/s13014-020-1481-z",
        ],
        "mapping": {"n stage": "uicc 7th edition n category"},
    },
    {
        "doi": [
            "https://doi.org/10.31557/APJCP.2020.21.5.1481",
            "https://doi.org/10.1186/s13014-020-1481-z",
        ],
        "mapping": {"t stage": "uicc 7th edition t category"},
    },
    {
        "doi": [
            "https://doi.org/10.1186/s13014-020-1481-z",
        ],
        "mapping": {"uicc": "uicc 7th edition stage"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.21925"],
        "mapping": {"m stage": "ajcc 6th 7th edition m category"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.21925"],
        "mapping": {"n stage": "ajcc 6th 7th edition n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/lary.21925"],
        "mapping": {"t stage": "ajcc 6th 7th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1186/1748-717X-8-21"],
        "mapping": {"n category": "ajcc 6th edition n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.28870"],
        "mapping": {
            "n classification": "ajcc 5th 6th 7th edition pathological n category"
        },
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.28870"],
        "mapping": {
            "t classification": "ajcc 5th 6th 7th edition pathological t category"
        },
    },
    {
        "doi": [
            "https://doi.org/10.1002/lary.28936",
            "https://doi.org/10.1177/01945998221120646",
        ],
        "mapping": {"n classification": "clinical n category"},
    },
    {
        "doi": [
            "https://doi.org/10.1177/01945998221120646",
            "https://doi.org/10.1177/0194599820973256",
        ],
        "mapping": {"t classification": "clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.clon.2010.08.027"],
        "mapping": {"m category": "clinical m category"},
    },
    {
        "doi": ["https://doi.org/10.3109/00016489.2014.968673"],
        "mapping": {"n stage": "ajcc 7th edition n category"},
    },
    {
        "doi": ["https://doi.org/10.3109/00016489.2014.968673"],
        "mapping": {"t stage": "ajcc 7th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1111/j.1754-9485.2012.02387.x"],
        "mapping": {"n stage": "uicc 6th edition n category"},
    },
    {
        "doi": [
            "https://doi.org/10.1111/j.1754-9485.2012.02387.x",
            "https://doi.org/10.1186/1748-717X-7-122",
        ],
        "mapping": {"t stage": "uicc 6th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.oraloncology.2014.09.015"],
        "mapping": {"n stage": "ajcc 7th edition clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.oraloncology.2014.09.015"],
        "mapping": {"t stage": "ajcc 7th edition clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1002/cam4.4204"],
        "mapping": {"n stage": "ajcc 6th edition clinical n category"},
    },
    {
        "doi": ["https://doi.org/10.1002/cam4.4204"],
        "mapping": {"t stage": "ajcc 6th edition clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.1007/s10552-017-0938-3"],
        "mapping": {"t class": "ajcc 6th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1002/hed.20303"],
        "mapping": {"t classification": "ajcc 6th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.1016/j.oraloncology.2018.07.019"],
        "mapping": {"t classification": "ajcc 7th edition clinical t category"},
    },
    {
        "doi": ["https://doi.org/10.6004/jnccn.2017.7001"],
        "mapping": {"t stage": "ajcc 8th edition t category"},
    },
    {
        "doi": ["https://doi.org/10.7314/APJCP.2016.17.4.1745"],
        "mapping": {"tumor stage": "clinical stage"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.23931"],
        "mapping": {"larynx": "larynx subsites"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.23931"],
        "mapping": {"oral cavity": "oral cavity subsites"},
    },
    {
        "doi": ["https://doi.org/10.1002/cncr.23931"],
        "mapping": {"oropharynx": "oropharynx subsites"},
    },
]

PERSON_MAPPING = {
    "ace 27 score": "adult comorbidity evaluation-27 scale",
    "alcohol consumption": "alcohol",
    "alcohol use": "alcohol",
    "alcohol use history": "alcohol",
    "charlson comorbidity index": "charlson comorbidity index score",
    "charlson comorbidity score": "charlson comorbidity index score",
    "charlson score": "charlson comorbidity index score",
    "charlson–deyo comorbidity score": "charlson-deyo comorbidity score",
    "charlson deyo": "charlson-deyo comorbidity score",
    "charlson deyo comorbidity": "charlson-deyo comorbidity score",
    "charlson deyo comorbidity count": "charlson-deyo comorbidity score",
    "charlson deyo comorbidity index": "charlson-deyo comorbidity score",
    "charlson deyo comorbidity score": "charlson-deyo comorbidity score",
    "charlson deyo score": "charlson-deyo comorbidity score",
    "comorbidity score": "charlson-deyo comorbidity score",
    "enrolled in clinical trial": "clinical trial participation",
    "participated in a clinical trial for head and neck cancer": "clinical trial participation",
    "participation in trial": "clinical trial participation",
    "comorbidities": "comorbidity",
    "comorbidity burden": "comorbidity",
    "number of comorbidities": "comorbidity",
    "distance": "distance to treatment facility",
    "distance from facility": "distance to treatment facility",
    "distance from reporting facility": "distance to treatment facility",
    "distance to facility": "distance to treatment facility",
    "distance to hospital": "distance to treatment facility",
    "distance to treating facility": "distance to treatment facility",
    "ecog ps": "ecog performance status",
    "performance status": "ecog performance status",
    "performance status (ecog)": "ecog performance status",
    "performance status ecog": "ecog performance status",
    "performance status ecog score": "ecog performance status",
    "hpv": "hpv status",
    "income level": "income",
    "health insurance": "insurance",
    "health insurance type": "insurance",
    "insurance status": "insurance",
    "insurance type": "insurance",
    "patient insurance": "insurance",
    "karnofsky": "karnofsky performance status",
    "median household income <20000 per year": "median household income by zip code <20000 per year",
    "median annual income": "median income",
    "median income quartile": "median income",
    "median household income quartile": "median income of patient's zip code",
    "zip code level income": "median income of patient's zip code",
    "census based income": "median income of patient's census tract",
    "median income of patient’s census tract": "median income of patient's census tract",
    "median income quintile": "median income of patient's census tract",
    "census region": "patient location",
    "county of residence": "patient location",
    "county population type": "patient location",
    "county type": "patient location",
    "location": "patient location",
    "location of diagnosis": "patient location",
    "region": "patient location",
    "region of residence": "patient location",
    "residence": "patient location",
    "rurality": "patient location",
    "seer region": "patient location",
    "urbanity": "patient location",
    "did not graduate from high school": "percentage of residents without a high school degree",
    "education (% without a high school diploma)": "percentage of residents without a high school degree",
    "education (no high school diploma)": "percentage of residents without a high school degree",
    "no high school degree": "percentage of residents without a high school degree",
    "percentage of patient's census tract without a high school degree": "percentage of residents without a high school degree in patient’s census tract",
    "adults in zip code without high school diploma": "percentage of residents without a high school degree in patient’s zip code",
    "no high school diploma": "percentage of residents without a high school degree in patient’s zip code",
    "zip code level education": "percentage of residents without a high school degree in patient’s zip code",
    "history of cancer": "previous cancer",
    "other malignancies": "previous cancer",
    "other tumor before angiosarcoma": "previous cancer",
    "gender": "sex",
    "habits": "smoking/alcohol",
    "history of smoking and/or drinking": "smoking/alcohol",
    "history of smoking": "smoking history",
    "prior smoking": "smoking history",
    "smoking": "smoking history",
    "smoking status": "smoking history",
    "tobacco": "smoking history",
    "registry": "tumor registry region",
    "diagnosis era": "year of diagnosis",
    "diagnosis year": "year of diagnosis",
    "incidence year": "year of diagnosis",
    "period of diagnosis": "year of diagnosis",
    "time period": "year of diagnosis",
    "year": "year of diagnosis",
    "year diagnosed": "year of diagnosis",
}

TUMOR_MAPPING = {
    "clinical nodal stage": "ajcc 6th edition clinical n category",
    "m class": "ajcc 6th edition m category",
    "n class": "ajcc 6th edition n category",
    "disease stage": "ajcc 6th edition stage",
    "ajcc t stage": "ajcc 6th edition t category",
    "ajcc 7th edition n stage": "ajcc 7th edition clinical n category",
    "overall pathological stage": "ajcc 7th edition pathological stage",
    "cancer stage": "ajcc 7th edition stage",
    "ajcc 7th edition t stage": "ajcc 7th edition t category",
    "ajcc n stage clinical": "ajcc clinical n category",
    "cn classification": "ajcc clinical n category",
    "clinical ajcc stage": "ajcc clinical stage",
    "ct classification": "ajcc clinical t category",
    "ajcc m stage": "ajcc m category",
    "ajcc pathologic n category": "ajcc pathological n category",
    "ajcc pathologic stage group": "ajcc pathological stage",
    "pathologic ajcc cancer stage": "ajcc pathological stage",
    "ajcc pathologic t category": "ajcc pathological t category",
    "pt stage": "ajcc pathological t category",
    "ajcc stage group": "ajcc stage",
    "ajcc stage of disease": "ajcc stage",
    "ajcc t classification": "ajcc t category",
    "cancer status": "cancer type",
    "tmn clinical m stage": "clinical m category",
    "clinical n classification": "clinical n category",
    "clinical n stage": "clinical n category",
    "tmn clinical n stage": "clinical n category",
    "initial clinical stage at scchn diagnosis": "clinical stage",
    "tnm clinical classification": "clinical stage",
    "clinical t classification": "clinical t category",
    "clinical t stage": "clinical t category",
    "tmn clinical t stage": "clinical t category",
    "invasion depth": "depth of invasion",
    "pattern of disease": "disease status",
    "historic stage a": "extent of disease by seer historic stage a",
    "grade of tumor": "grade",
    "grading": "grade",
    "histologic grade": "grade",
    "histological grade": "grade",
    "histology grade": "grade",
    "tumor differentiation": "grade",
    "tumor grade": "grade",
    "working formulation for the malignancy of nasopharyngeal carcinoma": "grade",
    "histologic subtype": "histology",
    "histology subtype": "histology",
    "histology of primary tumor": "histology",
    "histopathologic type": "histology",
    "histopathological subtype": "histology",
    "histopathology types": "histology",
    "human papillomavirus status": "hpv status",
    "hpv p16 status": "hpv status p16",
    "hpv serotype 16 or 18 status": "hpv status serotype 16 18",
    "local/locoregional recurrent, initial diagnosis stage i-iii": "local/locoregional recurrent status",
    "distant metastases": "m category",
    "m stage": "m category",
    "metastatic status": "m category",
    "distant metastasis site": "metastatic site",
    "secondary tumor diagnosis site": "metastatic site",
    "site for distant metastasis": "metastatic site",
    "present with distant metastasis": "metastatic site at presentation",
    "n": "n category",
    "n classification": "n category",
    "n classification on first diagnosis": "n category",
    "n stage": "n category",
    "node stage": "n category",
    "development of new primary tumor": "new primary",
    "nodal location": "nodal level",
    "positive node location": "nodal level",
    "node level at presentation": "nodal level at presentation",
    "lymph node status": "nodal status",
    "node status": "nodal status",
    "pathologic nodal involvement": "nodal status",
    "regional lymph node status": "nodal status",
    "pathologic n stage": "pathological n category",
    "pathological n stage": "pathological n category",
    "pn classification": "pathological n category",
    "pathologic t classification": "pathological t category",
    "pathologic t stage": "pathological t category",
    "pathological t stage": "pathological t category",
    "pt classification": "pathological t category",
    "positive margins": "positive margin status",
    "cancer site": "primary site",
    "disease site": "primary site",
    "localisation": "primary site",
    "location of primary tumor": "primary site",
    "mucosal scc anatomic subsite": "primary site",
    "primary anatomic site": "primary site",
    "primary subsite": "primary site",
    "primary tumor location": "primary site",
    "primary tumor site": "primary site",
    "site": "primary site",
    "site of primary tumor": "primary site",
    "subsite": "primary site",
    "tumor invasion site": "primary site",
    "tumor involved area": "primary site",
    "tumor location": "primary site",
    "tumor site": "primary site",
    "recurrence location": "recurrence site",
    "site of first recurrence": "recurrence site",
    "rn classification": "recurrence n category",
    "recurrent stage group": "recurrence stage",
    "rt classification": "recurrence t category",
    "tumor status at diagnosis": "resectability",
    "tumor size": "size",
    "tnm disease stage": "stage",
    "tumor stage": "stage",
    "disease stage at data capture": "stage at data capture",
    "disease stage at diagnosis": "stage at diagnosis",
    "group stage on first diagnosis": "stage on first diagnosis",
    "tumor stage at initial diagnosis": "stage on first diagnosis",
    "t": "t category",
    "t classification": "t category",
    "t stage": "t category",
    "t staging": "t category",
    "t classification on first diagnosis": "t category on first diagnosis",
    "diagnosis to data capture": "time from diagnosis to data capture",
    "who pathological subtype": "who histology",
}

TREATMENT_MAPPING = {
    "additional therapy": "additional treatment modality",
    "receipt of adjuvant chemotherapy": "adjuvant chemotherapy",
    "receipt of adjuvant radiotherapy": "adjuvant radiotherapy",
    "received adjuvant radiation therapy": "adjuvant radiotherapy",
    "use of non-drug treatments": "additional treatment modality",
    "received adjuvant chemoradiation therapy": "adjuvant chemoradiotherapy",
    "adjuvant therapy": "adjuvant treatment modality",
    "adjuvant treatment": "adjuvant treatment modality",
    "cancer­ directed treatments before metastatic scchn diagnosis": "cancer directed treatment modality prior to metastatic scchn diagnosis",
    "chemotherapy drug used": "chemotherapy agent",
    "chemotherapy drugs": "chemotherapy agent",
    "chemotherapy use": "chemotherapy agent",
    "chemotherapy regimen contain": "chemotherapy regimen agent",
    "chemotherapy stratified by drugs": "chemotherapy stratified by agent",
    "cisplatin administration": "cisplatin regimen",
    "complete planned radiotherapy course": "completed planned radiotherapy course",
    "concurrent chemoradiation": "concurrent chemoradiotherapy",
    "concurrent chemotherapy received": "concurrent chemoradiotherapy",
    "concurrent therapy with radiotherapy": "concurrent treatment",
    "technique of definitive radiotherapy": "definitive radiotherapy technique",
    "definitive treatment": "definitive treatment modality",
    "presence of extracapsular spread": "extracapsular spread",
    "feeding tube placement": "feeding tube",
    "1l treatment": "first line treatment",
    "first treatment": "first treatment modality",
    "fourth line with ps 0, 1, 2+": "fourth line treatment with ps 0, 1, 2+",
    "fraction number": "fraction",
    "number of fraction": "fraction",
    "fractionation method": "fractionation",
    "radiation fractionation": "fractionation",
    "induction chemotherapy agent": "induction chemotherapy regimen",
    "treatment intent": "intent",
    "line of drug treatment at point of data capture": "line of treatment at point of data capture",
    "locoregional treatment": "locoregional treatment modality",
    "lymphovascular space invasion": "lymphovascular invasion",
    "margin": "margin status",
    "margins": "margin status",
    "resection margin": "margin status",
    "surgical margin": "margin status",
    "surgical margins": "margin status",
    "surgical margin status": "margin status",
    "neck surgery": "neck dissection",
    "surgical management of neck": "neck dissection",
    "use of neck dissection": "neck dissection",
    "levels iv-v nodes": "nodal levels iv-v",
    "low neck nodes level 4 or 5": "nodal levels iv-v",
    "no of nodes examined": "number of nodes examined",
    "pathologic n stage": "pathological n category",
    "pathologic t stage": "pathological t category",
    "positive margin": "positive margin status",
    "positive margins": "positive margin status",
    "receipt of postoperative chemotherapy": "postoperative chemotherapy",
    "receipt of postoperative radiation": "postoperative radiotherapy",
    "primary mode of care": "primary treatment modality",
    "primary treatment": "primary treatment modality",
    "any radiation": "radiotherapy",
    "radiation therapy": "radiotherapy",
    "break during radiotherapy": "radiotherapy break",
    "radiation dose": "radiotherapy dose",
    "radiation dose received": "radiotherapy dose received",
    "elapsed time of radiotherapy": "radiotherapy duration",
    "overall radiotherapy duration": "radiotherapy duration",
    "radiotherapy days": "radiotherapy duration",
    "radiation modality": "radiotherapy modality",
    "radiation technique": "radiotherapy technique",
    "total radiation dosage": "radiotherapy total dose",
    "total radiotherapy dose": "radiotherapy total dose",
    "radiation type": "radiotherapy type",
    "reason for discontinuation of 1l": "reason for discontinuation of first line treatment",
    "reason for no surgery": "reasons for no surgery",
    "2l treatment": "second line treatment",
    "hnc related supportive care": "supportive treatment",
    "any surgery": "surgery",
    "hnc related surgery": "surgery",
    "main surgical procedure": "surgery",
    "surgery modality": "surgery",
    "surgery type": "surgery",
    "surgical treatment": "surgery",
    "regimen": "systemic therapy regimen",
    "systemic treatment regimen": "systemic therapy regimen",
    "treatment regimen": "systemic therapy regimen",
    "diagnosis to start of first-line drug therapy": "time from diagnosis to start of first-line treatment",
    "waiting time for treatment from diagnosis": "time from diagnosis to treatment",
    "end of 1st-line drug therapy to start of 2nd-line drug therapy": "time from end of first line treatment to start of second line treatment",
    "start of 1st-line platinum-based drug therapy to start of 2nd-line drug therapy": "time from start of first line platinum based treatment to start of second line treatment",
    "surgery to radiotherapy interval": "time from surgery to radiotherapy",
    "duration of therapy": "treatment duration",
    "curative treatment details": "treatment modality",
    "modality": "treatment modality",
    "overall treatment regimen": "treatment modality",
    "overall treatment strategy": "treatment modality",
    "retreatment of recurrence": "treatment modality for recurrence",
    "therapeutic regimen": "treatment modality",
    "therapy": "treatment modality",
    "therapy provided": "treatment modality",
    "treatment": "treatment modality",
    "treatment arm": "treatment modality",
    "treatment group": "treatment modality",
    "treatment modalities": "treatment modality",
    "treatment paradigm": "treatment modality",
    "treatment received": "treatment modality",
    "treatment selection": "treatment modality",
    "treatment type": "treatment modality",
    "treatment variation": "treatment modality",
    "type of treatment": "treatment modality",
}

HS_MAPPING = {
    "facility case volume": "facility volume",
    "hospital volume": "facility volume",
    "patient volume": "facility volume",
    "treatment center volume": "facility volume",
    "treatment center case volume": "facility volume",
    "hospital": "facility type",
    "hospital type": "facility type",
    "facility": "facility type",
    "practice setting": "facility type",
    "treatment center": "facility type",
    "treatment facility type": "facility type",
    "type of facility where radiation delivered": "facility type",
    "type of institution": "facility type",
    "hospital facility location": "facility location",
    "location": "facility location",
    "location of facility": "facility location",
    "region": "facility location",
    "treatment facility location": "facility location",
    "hospital size": "facility size",
    "hospital beds": "facility size",
    "hospital bed size": "facility size",
}

ALL_MAPPING = {
    "person": PERSON_MAPPING,
    "tumor": TUMOR_MAPPING,
    "treatment": TREATMENT_MAPPING,
    "health system": HS_MAPPING,
}

CUSTOM_ENTITY = {
    "assessment of stage": "diagnosis",
    "diagnosing physician": "health system",
    "hpv status tested": "diagnosis",
    "hpv testing": "diagnosis",
    "missing initial chest radiography or thoracic computed tomography scan to identify asymptomatic lung metastases": "diagnosis",
    "approved residency training program": "health system",
    "residency program": "health system",
    "tumor registry region": "health system",
    "patient location": "person",
    "year of diagnosis": "person",
    "positive margin status": "tumor",
    "time between initial diagnosis and index date": "treatment",
    "time from diagnosis to data capture": "treatment",
    "treatment at >1 facility": "treatment",
    "waiting time <1 month": "treatment",
    ">=6 positive nodes": "tumor",
    ">=two positive nodes": "tumor",
    "ajcc pathological n category": "tumor",
    "ajcc pathological t category": "tumor",
    "ct changed treatment": "treatment",
    "depth of invasion": "tumor",
    "extent of disease": "tumor",
    "extracapsular extension": "tumor",
    "extracapsular spread": "tumor",
    "extranodal extension": "tumor",
    "grade": "tumor",
    "hpv status": "tumor",
    "lymphovascular invasion": "tumor",
    "macroscopic extracapsular extension": "tumor",
    "number of positive nodes": "tumor",
    "pathological n category": "tumor",
    "pathological t category": "tumor",
    "pathologically positive lymph nodes": "tumor",
    "pathologic upstaged to": "tumor",
    "perineural invasion": "tumor",
    "premalignant lesions": "tumor",
    "related to lesion": "tumor",
    "total number of intermediate or high-risk features": "tumor",
    "lymph node resection": "treatment",
    "macroscopic residual tumor": "tumor",
    "extension": "tumor",
    "malignancy present": "tumor",
    "time from referral to first oncology visit": "diagnosis",
    "mouth": "tumor",
    "tongue": "tumor",
    "type of test": "diagnosis",
    "pathologic residual disease": "tumor",
    "high risk hpv status": "tumor",
    "level involved": "tumor",
    "nodal disease": "tumor",
    "margin status": "tumor",
    "lymph node examined": "tumor",
    "margin status in salvage streatment": "tumor",
    "nodal levels iv-v": "tumor",
    "number of examined nodes": "tumor",
    "number of nodes examined": "tumor",
    "prior radiotherapy": "treatment",
    "prior surgery": "treatment",
    "prior systemic therapy": "treatment",
    "distance from patient's census tract to treatment facility": "health system",
    "distance from the patient’s zip code to treatment facility": "health system",
    "distance to treatment facility": "health system",
}
